name: Crawler

on:
  push:
    branches: [ master ]

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Execute
      env:
        DATABASE_URL_FOR_CRAWLER: ${{ secrets.DATABASE_URL_FOR_CRAWLER }}
      run: |
        go run main.go
