name: Crawler

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL_FOR_CRAWLER: ${{ env.DATABASE_URL_FOR_CRAWLER }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        go build

    - name: Execute
      run: |
        ./schedule.crawler
